---

- hosts: all
  become: true
  tasks:

  - name: Install apache and php packages
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Start httpd service
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: Add firewall rule port 80
    command: firewall-cmd --add-port=80/tcp
